version: '3.9'

services:
    web:
        build: .
        hostname: noel
        ports:
            - "81:81"
    
    
    mongodb:
        image: mongo
        ports:
          - 27017:27017
        hostname: mongo
        environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=password
            
    mongo-express:
        image: mongo-express
        ports:
          - 8081:8081
        hostname: mongo-express
        environment:
          - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
          - ME_CONFIG_MONGODB_ADMINPASSWORD=password
          - ME_CONFIG_MONGODB_SERVER=mongodb
        restart: unless-stopped